swagger: "2.0"
info:
  description: "This is a simple Pokemon API implementation."
  version: "1.0.0"
  title: "ALTEA Pokemon API"
host: "altea-pokemon-api.herokuapp.com"
tags:
  - name: "pokemons"
    description: "Everything about your Pokemons"
schemes:
  - "https"
paths:
  /pokemons:
    get:
      tags:
        - "pokemons"
      summary: "Get all the pokemons"
      description: ""
      operationId: "getPokemons"
      produces:
        - "application/json"
      responses:
        200:
          description: "ok"
          schema:
            type: array
            items:
              $ref: "#/definitions/Pokemon"
  /pokemons/{pokemonId}:
    get:
      tags:
        - "pokemons"
      summary: "Get a pokemon by ID"
      description: "Returns a single Pokemon"
      operationId: "getPokemonById"
      produces:
        - "application/json"
      parameters:
        - name: "pokemonId"
          in: "path"
          description: "ID of Pokemon to return"
          required: true
          type: "integer"
          format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Pokemon"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Pokemon not found"
definitions:
  Pokemon:
    type: "object"
    required:
      - "id"
      - "name"
    properties:
      id:
        type: "integer"
        format: "int64"
        example: 25
      name:
        type: "string"
        example: "pikachu"
      sprites:
        type: "object"
        properties:
          front_default:
            type: string
            example: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/25.png"
          back_default:
            type: string
            example: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/25.png"
      stats:
        type: "object"
        properties:
          speed:
            type: "integer"
            format: "int64"
            example: "90"
          defense:
            type: "integer"
            format: "int64"
            example: 40
          attack:
            type: "integer"
            format: "int64"
            example: 55
          hp:
            type: "integer"
            format: "int64"
            example: 35